steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cdc_strategy_handler
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --allow-unauthenticated
      - --region=europe-central2
      - --vpc-connector=vpceuropeconnector
      - --egress-settings=all

options:
  logging: CLOUD_LOGGING_ONLY